111 importerror cannot import name gaussian from scipysignal (#112)
updated config to get arviz>0.18 requiring an update of python version to be larger than 3.10